source 'ssh://git@bitbucket.tomtomgroup.com:7999/lns/cocoapods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'routeAR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'TomTomOnlineSDKRouting'
  # Pods for routeAR

end
